"""中文翻译表。
用法：
    from lang import tr
    tr("vorpal blade")   # → "斩首之刃"
未收录名称原样返回英文，方便渐进翻译。
"""

NAMES = {
    'abbot': '修院院长',
    'acid': '酸液',
    'acid blob': '酸液团',
    'acolyte': '侍僧',
    'adornment': '装饰',
    'agate': '玛瑙',
    'aggravate monster': '引怪',
    'air elemental': '风元素',
    'aklys': '投索',
    'aleax': '阿莱克斯',
    'aligned priest': '阵营祭司',
    'amber': '琥珀',
    'amethyst': '紫水晶',
    'amnesia': '失忆',
    'amulet of change': '变化护符',
    'amulet of esp': '心灵感应护符',
    'amulet of life saving': '保命护符',
    'amulet of magical breathing': '魔法呼吸护符',
    'amulet of reflection': '反射护符',
    'amulet of restful sleep': '安眠护符',
    'amulet of strangulation': '绞杀护符',
    'amulet of unchanging': '不变护符',
    'amulet versus poison': '抗毒护符',
    'angel': '天使',
    'ape': '猿',
    'apple': '苹果',
    'apprentice': '学徒',
    'aquamarine': '海蓝宝石',
    'arch priest': '大主教',
    'arch-lich': '巫妖王',
    'archeologist': '考古学家',
    'archon': '执政官',
    'arrow': '箭',
    'ashikaga takauji': '足利尊氏',
    'asmodeus': '阿斯莫德',
    'athame': '仪式匕首',
    'attendant': '侍从',
    'axe': '斧',
    'baalzebub': '巴力西卜',
    'baby black dragon': '黑龙幼崽',
    'baby blue dragon': '蓝龙幼崽',
    'baby crocodile': '鳄鱼幼体',
    'baby gray dragon': '灰龙幼崽',
    'baby green dragon': '绿龙幼崽',
    'baby long worm': '长虫幼体',
    'baby orange dragon': '橙龙幼崽',
    'baby purple worm': '紫虫幼体',
    'baby red dragon': '红龙幼崽',
    'baby shimmering dragon': '闪光龙幼崽',
    'baby silver dragon': '银龙幼崽',
    'baby white dragon': '白龙幼崽',
    'baby yellow dragon': '黄龙幼崽',
    'balrog': '炎魔',
    'baluchitherium': '俾路支兽',
    'banana': '香蕉',
    'banded mail': '环带甲',
    'barbarian': '野蛮人',
    'barbed devil': '倒刺魔',
    'bardiche': '长柄斧',
    'barrow wight': '冢中尸鬼',
    'bat': '蝙蝠',
    'battle-axe': '战斧',
    'beartrap': '捕熊夹',
    'bec de corbin': '鸦嘴锤',
    'beholder': '眼魔',
    'bell': '铃铛',
    'bill-guisarme': '钩镰枪',
    'black dragon': '黑龙',
    'black light': '黑光',
    'black naga': '黑纳迦',
    'black naga hatchling': '黑纳迦幼体',
    'black opal': '黑欧泊',
    'black pudding': '黑布丁',
    'black unicorn': '黑独角兽',
    'blank paper': '空白纸',
    'blindfold': '眼罩',
    'blindness': '致盲',
    'blue dragon': '蓝龙',
    'blue jelly': '蓝果冻',
    'bone devil': '骨魔',
    'boomerang': '回旋镖',
    'booze': '烈酒',
    'brass lantern': '黄铜提灯',
    'broadsword': '阔剑',
    'bronze plate mail': '青铜板甲',
    'brown mold': '棕霉',
    'brown pudding': '棕布丁',
    'bugbear': '熊地精',
    'bugle': '军号',
    'bullwhip': '牛皮鞭',
    'c-ration': 'C 口粮',
    'can of grease': '一罐油脂',
    'cancellation': '消除',
    'candy bar': '糖棒',
    'captain': '上尉',
    'carnivorous ape': '食肉猿',
    'carrot': '胡萝卜',
    'cave spider': '洞穴蜘蛛',
    'caveman': '原始男',
    'cavewoman': '原始女',
    'centipede': '蜈蚣',
    'cerberus': '刻耳柏洛斯',
    'chain mail': '锁子甲',
    'chameleon': '变色龙',
    'charging': '充能',
    'charon': '卡戎',
    'chickatrice': '小鸡蛇怪',
    'chieftain': '酋长',
    'chromatic dragon': '彩色龙',
    'chrysoberyl': '金绿宝石',
    'citrine': '黄水晶',
    'clay golem': '泥魔像',
    'cloak': '斗篷',
    'clove of garlic': '一瓣大蒜',
    'club': '木棒',
    'cobra': '眼镜蛇',
    'cockatrice': '鸡蛇怪',
    'cold': '寒冰',
    'cold resistance': '抗寒',
    'conflict': '冲突',
    'confuse monster': '混乱怪物',
    'confusion': '混乱',
    'corpse': '尸体',
    'couatl': '羽蛇',
    'coyote': '郊狼',
    'cram ration': '压缩口粮',
    'cream pie': '奶油派',
    'create monster': '创造怪物',
    'credit card': '信用卡',
    'crocodile': '鳄鱼',
    'croesus': '克罗伊斯',
    'crysknife': '水晶刀',
    'crystal ball': '水晶球',
    'crystal plate mail': '水晶板甲',
    'cyclops': '独眼巨人',
    'dagger': '匕首',
    'dark one': '黑暗者',
    'dart': '飞镖',
    'death': '死亡',
    'demilich': '半巫妖',
    'demogorgon': '狄摩高根',
    'destroy armor': '摧毁护甲',
    'diamond': '钻石',
    'digging': '挖掘',
    'dilithium crystal': '二锂水晶',
    'dingo': '澳洲野犬',
    'disenchanter': '解魔怪',
    'dispater': '迪斯帕特',
    'djinni': '神灯精灵',
    'dog': '狗',
    'doppelganger': '二重身',
    'dragon scale mail': '龙鳞甲',
    'drum of earthquake': '地震鼓',
    'dust vortex': '尘旋风',
    'dwarf': '矮人',
    'dwarf king': '矮人王',
    'dwarf lord': '矮人领主',
    'dwarf mummy': '矮人木乃伊',
    'dwarf zombie': '矮人僵尸',
    'dwarvish mattock': '矮人鹤嘴锄',
    'dwarvish mithril-coat': '矮人秘银甲',
    'dwarvish short sword': '矮人短剑',
    'dwarvish spear': '矮人长矛',
    'earendil': '埃雅仁迪尔',
    'earth': '大地',
    'earth elemental': '土元素',
    'egg': '蛋',
    'electric eel': '电鳗',
    'elf': '精灵',
    'elf mummy': '精灵木乃伊',
    'elf zombie': '精灵僵尸',
    'elf-lord': '精灵领主',
    'elven broadsword': '精灵阔剑',
    'elven dagger': '精灵匕首',
    'elven mithril-coat': '精灵秘银甲',
    'elven short sword': '精灵短剑',
    'elven spear': '精灵长矛',
    'elvenking': '精灵王',
    'elwing': '埃尔汶',
    'emerald': '祖母绿',
    'enchant armor': '附魔护甲',
    'enchant weapon': '附魔武器',
    'energy vortex': '能量旋风',
    'enlightenment': '启蒙',
    'erinys': '复仇女神',
    'ettin': '双头巨人',
    'ettin mummy': '双头巨人木乃伊',
    'ettin zombie': '双头巨人僵尸',
    'eucalyptus leaf': '桉树叶',
    'excalibur': '圣剑·断钢',
    'expensive camera': '昂贵相机',
    'extra healing': '高级治疗',
    'famine': '饥荒',
    'fauchard': '长柄镰',
    'figurine': '小雕像',
    'fire': '火焰',
    'fire ant': '火蚁',
    'fire elemental': '火元素',
    'fire giant': '火巨人',
    'fire horn': '火焰号角',
    'fire resistance': '抗火',
    'fire vortex': '火旋风',
    'flail': '连枷',
    'flaming sphere': '火球',
    'flesh golem': '血肉魔像',
    'flint': '燧石',
    'floating eye': '浮眼',
    'fluorite': '萤石',
    'fog cloud': '雾云',
    'food detection': '侦测食物',
    'food ration': '口粮',
    'forest centaur': '森林半人马',
    'fortune cookie': '幸运饼干',
    'fox': '狐狸',
    'free action': '自由行动',
    'freezing sphere': '冰球',
    'frost giant': '霜巨人',
    'frost horn': '冰霜号角',
    'fruit juice': '果汁',
    'full healing': '完全治疗',
    'gain ability': '获得能力',
    'gain constitution': '体质',
    'gain energy': '获得能量',
    'gain level': '提升等级',
    'gain strength': '力量',
    'gargoyle': '石像鬼',
    'garnet': '石榴石',
    'garter snake': '束带蛇',
    'gas spore': '毒气孢子',
    'gecko': '壁虎',
    'gelatinous cube': '胶质方块',
    'genocide': '灭绝',
    'geryon': '革律翁',
    'ghost': '幽灵',
    'ghoul': '食尸鬼',
    'giant': '巨人',
    'giant ant': '巨蚁',
    'giant bat': '巨蝙蝠',
    'giant beetle': '巨甲虫',
    'giant eel': '巨鳗',
    'giant mimic': '巨宝箱怪',
    'giant mummy': '巨人木乃伊',
    'giant rat': '巨鼠',
    'giant spider': '巨蜘蛛',
    'giant zombie': '巨人僵尸',
    'glaive': '大刀',
    'glass golem': '玻璃魔像',
    'glass piercer': '玻璃穿心虫',
    'glob of black pudding': '黑布丁团',
    'glob of brown pudding': '棕布丁团',
    'glob of gray ooze': '灰泥怪团',
    'glob of green slime': '绿史莱姆团',
    'gnome': '侏儒',
    'gnome king': '侏儒王',
    'gnome lord': '侏儒领主',
    'gnome mummy': '侏儒木乃伊',
    'gnome zombie': '侏儒僵尸',
    'gnomish wizard': '侏儒巫师',
    'goblin': '哥布林',
    'goblin king': '哥布林王',
    'gold detection': '侦测金币',
    'gold golem': '金魔像',
    'gold piece': '金币',
    'golden naga': '金纳迦',
    'golden naga hatchling': '金纳迦幼体',
    'grand master': '大宗师',
    'gray dragon': '灰龙',
    'gray ooze': '灰泥怪',
    'gray unicorn': '灰独角兽',
    'green dragon': '绿龙',
    'green mold': '绿霉',
    'green slime': '绿史莱姆',
    'green-elf': '绿精灵',
    'gremlin': '小妖精',
    'grey-elf': '灰精灵',
    'grid bug': '电网虫',
    'guard': '守卫',
    'guardian naga': '守卫纳迦',
    'guardian naga hatchling': '守卫纳迦幼体',
    'guide': '向导',
    'guisarme': '钩镰',
    'halberd': '戟',
    'hallucination': '幻觉',
    'hawaiian shirt': '夏威夷衫',
    'healer': '治疗师',
    'healing': '治疗',
    'hell hound': '地狱犬',
    'hell hound pup': '地狱犬崽',
    'helmet': '头盔',
    'hezrou': '蟾蜍魔',
    'high priest': '大祭司',
    'high-elf': '高等精灵',
    'hill giant': '丘陵巨人',
    'hill orc': '丘陵兽人',
    'hippocrates': '希波克拉底',
    'hobbit': '霍比特人',
    'hobgoblin': '大哥布林',
    'homunculus': '人造人',
    'horn of plenty': '丰饶之角',
    'horned devil': '角魔',
    'horse': '马',
    'housecat': '家猫',
    'huge chunk of meat': '大块肉',
    'human': '人类',
    'human mummy': '人类木乃伊',
    'human zombie': '人类僵尸',
    'hunger': '饥饿',
    'hunter': '猎人',
    'ice devil': '冰魔',
    'ice troll': '冰巨魔',
    'ice vortex': '冰旋风',
    'identify': '鉴定',
    'iguana': '鬣蜥',
    'imp': '小恶魔',
    'increase accuracy': '精准',
    'increase damage': '伤害',
    'incubus': '梦魔',
    'invisibility': '隐形',
    'iron golem': '铁魔像',
    'iron piercer': '铁穿心虫',
    'ixoth': '伊索斯',
    'jabberwock': '贾巴沃克',
    'jacinth': '红锆石',
    'jackal': '豺狼',
    'jade': '翡翠',
    'jaguar': '美洲豹',
    'jasper': '碧玉',
    'javelin': '标枪',
    'jellyfish': '水母',
    'jet': '黑玉',
    'juiblex': '朱伊布莱克斯',
    'k-ration': 'K 口粮',
    'katana': '武士刀',
    'kelp frond': '海带叶',
    'keystone kop': '基斯顿警察',
    'ki-rin': '麒麟',
    'killer bee': '杀人蜂',
    'king arthur': '亚瑟王',
    'kitten': '小猫',
    'knife': '小刀',
    'knight': '骑士',
    'kobold': '狗头人',
    'kobold lord': '狗头人领主',
    'kobold mummy': '狗头人木乃伊',
    'kobold shaman': '狗头人萨满',
    'kobold zombie': '狗头人僵尸',
    'kop kaptain': '警察队长',
    'kop lieutenant': '警察中尉',
    'kop sergeant': '警察中士',
    'kraken': '海怪',
    'lance': '骑枪',
    'land mine': '地雷',
    'large cat': '大猫',
    'large dog': '大狗',
    'large kobold': '大狗头人',
    'large mimic': '大宝箱怪',
    'leash': '皮带',
    'leather armor': '皮甲',
    'leather drum': '皮鼓',
    'leather golem': '皮魔像',
    'leather jacket': '皮夹克',
    'lembas wafer': '兰巴斯薄饼',
    'lemure': '游魂',
    'lenses': '镜片',
    'leocrotta': '豹牛兽',
    'leprechaun': '矮妖精',
    'levitation': '浮空',
    'lich': '巫妖',
    'lichen': '地衣',
    'lieutenant': '中尉',
    'light': '光亮',
    'lightning': '闪电',
    'little dog': '小狗',
    'lizard': '蜥蜴',
    'loadstone': '负重石',
    'lock pick': '开锁工具',
    'locking': '上锁',
    'long sword': '长剑',
    'long worm': '长虫',
    'long worm tail': '长虫尾',
    'lord carnarvon': '卡那封勋爵',
    'lord sato': '佐藤大人',
    'lord surtur': '苏尔特尔',
    'lucern hammer': '瑞士戟',
    'luckstone': '幸运石',
    'lump of royal jelly': '蜂王浆',
    'lurker above': '潜伏者',
    'lynx': '猞猁',
    'mace': '钉锤',
    'magic flute': '魔法笛',
    'magic harp': '魔法竖琴',
    'magic lamp': '魔法灯',
    'magic mapping': '魔法地图',
    'magic marker': '魔法笔',
    'magic missile': '魔法飞弹',
    'magic whistle': '魔法哨',
    'mail': '邮件',
    'mail daemon': '邮件恶魔',
    'make invisible': '隐形术',
    'manes': '亡魂',
    'marilith': '六臂蛇魔',
    'master assassin': '刺客大师',
    'master kaen': '凯恩大师',
    'master lich': '大巫妖',
    'master mind flayer': '夺心魔主',
    'master of thieves': '盗贼大师',
    'mastodon': '乳齿象',
    'meat stick': '肉条',
    'meatball': '肉丸',
    'medusa': '美杜莎',
    'melon': '甜瓜',
    'mind flayer': '夺心魔',
    'minion of huhetotl': '胡胡特特尔仆从',
    'minotaur': '弥诺陶洛斯',
    'mirror': '镜子',
    'monk': '武僧',
    'monkey': '猴子',
    'monster detection': '侦测怪物',
    'mordor orc': '魔多兽人',
    'morning star': '晨星锤',
    'mountain centaur': '山地半人马',
    'mountain nymph': '山仙女',
    'mumak': '猛犸',
    'nalfeshnee': '野猪魔',
    'nalzok': '纳尔佐克',
    'nazgul': '戒灵',
    'neanderthal': '尼安德特人',
    'neferet the green': '绿衣奈菲瑞特',
    'newt': '蝾螈',
    'ninja': '忍者',
    'norn': '诺恩',
    'nothing': '无用',
    'nurse': '护士',
    'object detection': '侦测物品',
    'obsidian': '黑曜石',
    'ochre jelly': '赭色果冻',
    'ogre': '食人魔',
    'ogre king': '食人魔王',
    'ogre lord': '食人魔领主',
    'oil': '油',
    'oil lamp': '油灯',
    'olog-hai': '奥洛格海',
    'opal': '欧泊',
    'opening': '开锁',
    'oracle': '神谕',
    'orange': '橙子',
    'orange dragon': '橙龙',
    'orc': '兽人',
    'orc mummy': '兽人木乃伊',
    'orc shaman': '兽人萨满',
    'orc zombie': '兽人僵尸',
    'orc-captain': '兽人队长',
    'orcish chain mail': '兽人锁子甲',
    'orcish dagger': '兽人匕首',
    'orcish ring mail': '兽人环甲',
    'orcish short sword': '兽人短剑',
    'orcish spear': '兽人长矛',
    'orcus': '奥库斯',
    'orion': '俄里翁',
    'owlbear': '枭熊',
    'page': '侍童',
    'pancake': '煎饼',
    'panther': '黑豹',
    'paper golem': '纸魔像',
    'paralysis': '麻痹',
    'partisan': '长柄矛',
    'pear': '梨',
    'pelias': '佩利阿斯',
    'pestilence': '瘟疫',
    'piranha': '食人鱼',
    'pit fiend': '深渊魔君',
    'pit viper': '蝰蛇',
    'plains centaur': '平原半人马',
    'plate mail': '板甲',
    'poison resistance': '抗毒',
    'polymorph': '变形',
    'polymorph control': '变形控制',
    'pony': '小马',
    'priest': '祭司',
    'priestess': '女祭司',
    'prisoner': '囚犯',
    'probing': '探查',
    'protection': '保护',
    'protection from shape changers': '防变形',
    'punishment': '惩罚',
    'purple worm': '紫虫',
    'pyrolisk': '火鸡蛇',
    'python': '蟒蛇',
    'quantum mechanic': '量子机械师',
    'quarterstaff': '长棍',
    'quasit': '夸塞魔',
    'queen bee': '蜂后',
    'quivering blob': '颤动团',
    'rabid rat': '狂犬鼠',
    'ranger': '游侠',
    'ranseur': '三叉长矛',
    'raven': '渡鸦',
    'red dragon': '红龙',
    'red mold': '红霉',
    'red naga': '红纳迦',
    'red naga hatchling': '红纳迦幼体',
    'regeneration': '再生',
    'remove curse': '移除诅咒',
    'restore ability': '恢复能力',
    'ring mail': '环甲',
    'robe': '长袍',
    'rock': '岩石',
    'rock mole': '岩鼹鼠',
    'rock piercer': '岩石穿心虫',
    'rock troll': '岩巨魔',
    'rogue': '盗贼',
    'rope golem': '绳魔像',
    'roshi': '老师',
    'rothe': '洛斯牛',
    'rubber hose': '橡胶管',
    'ruby': '红宝石',
    'runesword': '符文剑',
    'rust monster': '锈蚀怪',
    'saddle': '马鞍',
    'salamander': '火蜥蜴',
    'samurai': '武士',
    'sandestin': '沙灵',
    'sapphire': '蓝宝石',
    'sasquatch': '大脚怪',
    'scale mail': '鳞甲',
    'scalpel': '手术刀',
    'scare monster': '恐吓怪物',
    'scimitar': '弯刀',
    'scorpion': '蝎子',
    'scorpius': '天蝎',
    'searching': '搜寻',
    'secret door detection': '侦测密门',
    'see invisible': '识破隐形',
    'sergeant': '中士',
    'sewer rat': '下水道鼠',
    'shade': '阴魂',
    'shaman karnov': '萨满卡尔诺夫',
    'shark': '鲨鱼',
    'shield': '盾牌',
    'shimmering dragon': '闪光龙',
    'shock resistance': '抗电',
    'shocking sphere': '电球',
    'shopkeeper': '店主',
    'short sword': '短剑',
    'shrieker': '尖啸菌',
    'shuriken': '手里剑',
    'sickness': '疾病',
    'silver dagger': '银匕首',
    'silver dragon': '银龙',
    'silver saber': '银刀',
    'silver spear': '银长矛',
    'skeleton': '骷髅',
    'skeleton key': '万能钥匙',
    'sleep': '睡眠',
    'sleeping': '睡眠',
    'slime mold': '黏菌',
    'slow digestion': '减缓消化',
    'slow monster': '减速怪物',
    'small mimic': '小宝箱怪',
    'snake': '蛇',
    'soldier': '士兵',
    'soldier ant': '兵蚁',
    'spear': '长矛',
    'speed': '加速',
    'speed monster': '加速怪物',
    'spetum': '战戟',
    'splint mail': '夹板甲',
    'spotted jelly': '斑点果冻',
    'sprig of wolfsbane': '乌头草',
    'stalker': '潜行者',
    'stealth': '潜行',
    'steam vortex': '蒸汽旋风',
    'stethoscope': '听诊器',
    'stiletto': '刺刀',
    'stinking cloud': '臭云',
    'stone giant': '石巨人',
    'stone golem': '石魔像',
    'storm giant': '风暴巨人',
    'straw golem': '稻草魔像',
    'striking': '打击',
    'studded leather armor': '镶钉皮甲',
    'student': '学徒',
    'succubus': '魅魔',
    'sustain ability': '属性维持',
    't-shirt': 'T恤',
    'tallow candle': '牛脂蜡烛',
    'taming': '驯服',
    'teleport control': '传送控制',
    'teleportation': '传送',
    'tengu': '天狗',
    'thoth amon': '图特阿蒙',
    'thug': '恶棍',
    'tiger': '老虎',
    'tin': '罐头',
    'tin opener': '开罐器',
    'tin whistle': '锡哨',
    'tinning kit': '罐头工具',
    'titan': '泰坦',
    'titanothere': '雷兽',
    'tooled horn': '雕花号角',
    'topaz': '黄玉',
    'touchstone': '试金石',
    'tourist': '观光客',
    'towel': '毛巾',
    'trapper': '捕猎者',
    'trident': '三叉戟',
    'tripe ration': '内脏口粮',
    'troll': '巨魔',
    'tsurugi': '太刀',
    'turquoise': '绿松石',
    'two-handed sword': '双手剑',
    'twoflower': '双花',
    'umber hulk': '幽暗怪',
    'undead turning': '驱散亡灵',
    'uruk-hai': '强兽人',
    'valkyrie': '女武神',
    'vampire': '吸血鬼',
    'vampire bat': '吸血蝙蝠',
    'vampire lord': '吸血鬼领主',
    'vampire mage': '吸血鬼法师',
    'violet fungus': '紫菌',
    'vlad the impaler': '穿刺公弗拉德',
    'vorpal blade': '斩首之刃',
    'vorpal jabberwock': '斩首贾巴沃克',
    'voulge': '阔头枪',
    'vrock': '秃鹫魔',
    'war hammer': '战锤',
    'warg': '座狼',
    'warhorse': '战马',
    'warning': '警示',
    'warrior': '战士',
    'watch captain': '巡夜队长',
    'watchman': '巡夜人',
    'water': '水',
    'water demon': '水魔',
    'water elemental': '水元素',
    'water moccasin': '水蝮蛇',
    'water nymph': '水仙女',
    'water troll': '水巨魔',
    'wax candle': '蜡蜡烛',
    'werejackal': '豺狼人',
    'wererat': '鼠人',
    'werewolf': '狼人',
    'whip': '鞭',
    'white dragon': '白龙',
    'white unicorn': '白独角兽',
    'winged gargoyle': '翼石像鬼',
    'winter wolf': '冬狼',
    'winter wolf cub': '冬狼崽',
    'wishing': '许愿',
    'wizard': '巫师',
    'wizard of yendor': '叶诺德巫师',
    'wolf': '狼',
    'wood golem': '木魔像',
    'wood nymph': '木仙女',
    'woodchuck': '土拨鼠',
    'wooden flute': '木笛',
    'wooden harp': '木竖琴',
    'woodland-elf': '林地精灵',
    'worm tooth': '蠕虫牙',
    'worthless piece of black glass': '黑玻璃（不值钱）',
    'worthless piece of blue glass': '蓝玻璃（不值钱）',
    'worthless piece of green glass': '绿玻璃（不值钱）',
    'worthless piece of orange glass': '橙玻璃（不值钱）',
    'worthless piece of red glass': '红玻璃（不值钱）',
    'worthless piece of violet glass': '紫玻璃（不值钱）',
    'worthless piece of white glass': '白玻璃（不值钱）',
    'worthless piece of yellow glass': '黄玻璃（不值钱）',
    'worthless piece of yellowish brown glass': '黄褐玻璃（不值钱）',
    'wraith': '幽魂',
    'wumpus': '温帕斯',
    'xan': '赞仙',
    'xorn': '索尔石怪',
    'yeenoghu': '耶诺古',
    'yellow dragon': '黄龙',
    'yellow light': '黄光',
    'yellow mold': '黄霉',
    'yeti': '雪人',
    'zruty': '兹鲁提',
}


def tr(name):
    if not name:
        return name
    return NAMES.get(str(name).lower(), name)


def _dump_missing():
    """导出所有未翻译的名称，用于补表"""
    import json
    from pathlib import Path
    f = Path(__file__).parent / "data" / "nethack_data.json"
    d = json.loads(f.read_text())
    miss_items, miss_mons = [], []
    for it in d.get("items", []):
        n = it.get("name")
        if n and n.lower() not in NAMES:
            miss_items.append((it.get("class"), n))
    for m in d.get("monsters", []):
        n = m.get("name")
        if n and n.lower() not in NAMES:
            miss_mons.append(n)
    print("# ===== ITEMS (%d) =====" % len(miss_items))
    for cls, n in sorted(miss_items):
        print(f'{cls:8} {n!r}')
    print()
    print("# ===== MONSTERS (%d) =====" % len(miss_mons))
    for n in sorted(miss_mons):
        print(repr(n))


if __name__ == "__main__":
    _dump_missing()


# ---------- 显示宽度工具 ----------
import unicodedata


def dwidth(s):
    """字符串在终端里的显示宽度（中文算 2）"""
    w = 0
    for ch in str(s):
        w += 2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1
    return w


def pad(s, width, align="left"):
    """按显示宽度补空格到 width"""
    s = str(s)
    n = width - dwidth(s)
    if n <= 0:
        return s
    if align == "right":
        return " " * n + s
    if align == "center":
        l = n // 2
        return " " * l + s + " " * (n - l)
    return s + " " * n


def truncate(s, width):
    """按显示宽度截断，不切半个汉字"""
    s = str(s)
    w = 0
    out = []
    for ch in s:
        cw = 2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1
        if w + cw > width:
            break
        out.append(ch)
        w += cw
    return "".join(out)
